key_mapping:
  esc: "{VK_ESCAPE}"
  sel: "{VK_NUMPAD0}"
  menu_up: "{VK_NUMPAD8}"
  menu_down: "{VK_NUMPAD2}"
  goto_submenu: "'"
  tnpc: "1"
  taf: "2"
  single_macro: "3"
  double_macro_1: "5"
  double_macro_2: "6"
  eat_food: "7"
window_title: FINAL FANTASY XIV
target_process: ffxiv_dx11.exe
eat_food: False
meat_and_mead: 0 # valid options are 0 for off, 1 for meat and mead 1, 2 for meat and mead 2
per_run_delay: 5.0
post_food_delay: 5.0